-- Enable extensions (Supabase typically has vector preinstalled)
create extension if not exists pg_trgm;
create extension if not exists vector;

-- Products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  store_name text not null,
  category text,
  embedding vector(768)
);

-- Trigram index for fuzzy search
create index if not exists idx_products_name_trgm on public.products using gin (name gin_trgm_ops);

-- Vector index for ANN search (use appropriate lists for your data size)
create index if not exists idx_products_embedding on public.products using ivfflat (embedding vector_l2_ops) with (lists = 50);